### ISSUE TITLE
little problem with code in knowledge_util.py

### ISSUE THREAD

**Issue by tudouzhao** [SixingPKU/ACL2020-ConKADI#2]
for line in lines:
            items = line.strip('\n').split()
            for i in [0, 1, 3]:
                items[i] = int(entity_dict.get(items[i], 0))
            items[2] = int(relation_dict.get(items[2])) + len(entity_dict)  # realtion和 entity共用一个列表

            entity_fact.append(items[1:])
            entity_target.append(items[0])  # uni ids
when dealing with fifth line, error occurs like this:
Traceback (most recent call last):
  File "/Users/yyzyhc/Downloads/ACL2020-ConKADI-master/knowledge_utils.py", line 160, in <module>
    load_knowledge_graph(hparams)
Total Entity-Fact : 696466
  File "/Users/yyzyhc/Downloads/ACL2020-ConKADI-master/knowledge_utils.py", line 141, in load_knowledge_graph
    items[2] = int(relation_dict.get(items[2])) + len(entity_dict)  # realtion和 entity共用一个列表
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by tudouzhao** [comment]
actually ,I think this is due to file relaction_vocab.txt, which does not have a line containing '#NH'

**Comment by pku-sixing** [comment]
> actually ,I think this is due to file relaction_vocab.txt, which does not have a line containing '#NH'

So, have you solved it?

**Comment by tudouzhao** [comment]
no, I am not sure whether it is useful to do little change here.Now, I am trying to redo your experiment and examine.
